In [1]:
#1. Create a null array of size 10 but the fifth value which is 1
import numpy as np
a = [None]*10
a[4]=1
np.array(a)
print(a)


[None, None, None, None, 1, None, None, None, None, None]


In [2]:
#2. Reverse a above created array (first element becomes last)
b = a[::-1]
print(b)

[None, None, None, None, None, 1, None, None, None, None]


In [3]:
#3. Create a 3x3 matrix with values ranging from 0 to 8
    #NC: I didnt know if we were supposed to do the values 0-8 or random values between 0 and 8 so I did both
c=np.arange(9).reshape((3,3))  
d = np.random.randint(low=0, high=8, size=(3,3))

print(c)
print()
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[2 0 7]
 [6 3 5]
 [3 1 3]]


In [4]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]
e = [1,2,0,0,4,0]
f = np.nonzero(e)
print(f)

(array([0, 1, 4], dtype=int64),)


In [5]:
#5. Create a 3x3x3 array with random values
g = np.random.random((3,3,3))
print(g)

[[[0.7023926  0.94792094 0.46762904]
  [0.03641502 0.40544578 0.8215634 ]
  [0.72076778 0.73833419 0.40106012]]

 [[0.56528151 0.57791634 0.41529773]
  [0.45019646 0.65362858 0.99233051]
  [0.48556    0.51568775 0.99207566]]

 [[0.89051721 0.67097497 0.76266156]
  [0.72032852 0.88778159 0.23553844]
  [0.74132628 0.81235079 0.85080199]]]


In [6]:
#6. Create a 10x10 array with random values and find the minimum and maximum values
h = np.random.randint(low=0,high=100,size=(10,10))
print(h)
a=np.min(h)
b=np.max(h)
print(f"Min is {a}")
print(f"Max is {b}")

[[41 56 82 70 17 97 79 99 13 31]
 [12 46 56 56 70 88 40 90 43 37]
 [24 33 30 41 43 42 47 63  9 89]
 [13 96 48 35 71 65 32 30 53 86]
 [96 51 55 70 29 79  2 76 54 72]
 [46 58 86 23 76 76 78 19  0 53]
 [ 9 50 49 44 13 34 44 19 86  2]
 [19 13 57 80 53 98 76 63 34 52]
 [ 9 63 69 51 13 70 49 98 21  6]
 [83 68 47 16 33 95 57  3  7  1]]
Min is 0
Max is 99


In [7]:
#7. Create a random vector of size 30 and find the mean value
i=np.random.random(30)
print(i)
a = np.mean(i)
print(f"Mean is {a}")

[0.89250353 0.49223992 0.47118566 0.4237498  0.98816801 0.18472784
 0.10593212 0.16371364 0.43747835 0.88961747 0.45363998 0.71880985
 0.7628771  0.85591497 0.04173453 0.43231032 0.3526083  0.86543657
 0.07410296 0.84938159 0.11431455 0.63265674 0.13160304 0.09922387
 0.05401521 0.47516486 0.17954068 0.4547108  0.37329385 0.03850794]
Mean is 0.4336388024520505


In [8]:
#8. Create a 2d array with 1 on the border and 0 inside
j = np.array([[1,1,1,1], [1,0,0,1],[1,0,0,1],[1,1,1,1]])
print(j)

#alternative way:
k=np.zeros((4,4),dtype=int)
k[:, 0] =  1
k[:, 3] =  1
k[0, :] =  1
k[3, :] =  1
print(k)

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]
[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


In [9]:
#9. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
l=np.random.randint(low=0,high=10,size=(5,3))
m=np.random.randint(low=0,high=10,size=(3,2))
n= np.dot(l,m)
print(l)
print(m)
print(n)

[[6 6 6]
 [0 2 2]
 [0 9 5]
 [7 5 8]
 [5 9 6]]
[[5 4]
 [9 9]
 [0 5]]
[[ 84 108]
 [ 18  28]
 [ 81 106]
 [ 80 113]
 [106 131]]


In [10]:
#10. Extract the integer part of a random array
o = np.random.random(20)*3.5
print(o)
np.floor(o)



[1.16093831 1.45329381 3.2327539  1.79690917 0.0113563  0.32072827
 1.22220882 1.60862759 3.0273738  3.47567774 2.64540257 1.20351802
 0.14094123 0.47522844 2.02476403 0.15790894 2.52566048 2.7237774
 1.32000307 0.61032982]


array([1., 1., 3., 1., 0., 0., 1., 1., 3., 3., 2., 1., 0., 0., 2., 0., 2.,
       2., 1., 0.])

In [11]:
#11. Create a 5x5 matrix with row values ranging from 0 to 4
p=np.random.randint(low=0, high=4, size=(5,5))
print(p)

[[2 3 1 1 2]
 [3 1 0 2 3]
 [1 0 0 0 3]
 [0 0 1 0 0]
 [2 2 1 0 0]]


In [12]:
#12.  Create a random vector of size 10 and sort it
q=np.random.randint(low=0, high=100, size=(10))
print(q)
np.sort(q)


[11 77 98 75  9 45 61 24 62 74]


array([ 9, 11, 24, 45, 61, 62, 74, 75, 77, 98])

In [13]:
#13. Consider two random array A anb B, check if they are equal.
r=np.random.randint(low=0, high=100, size=(10))
s=np.random.randint(low=0, high=100, size=(10))
print(r)
print(s)
np.array_equal(r, s)


[76 92 24 13 15 49 72 52 99 51]
[56 48 42 17 25 33 35 66 39 33]


False

In [14]:
#14. How to tell if a given 2D array has null columns?
t = np.random.randint(low=0, high=10,size=(1,10))
print(t)
check_t=np.isnan(t)
print((check_t.any(axis=0)).any())


[[3 5 1 0 0 1 3 7 9 3]]
False


In [15]:
#15. Considering a four dimensions array, how to get sum over the last two axis at once?
    #NC: Dont really understand this one
u = np.arange(16).reshape((2,2,2,2))
print(u) 
u.sum(axis=(2, 3))

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


array([[ 6, 22],
       [38, 54]])

In [16]:
#16. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)?
v=np.arange(75).reshape((5,5,3))
print(v)
w=np.arange(25).reshape((5,5))
print(w)

print('You cant multiply them because the dimensions dont line up')

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]]

 [[45 46 47]
  [48 49 50]
  [51 52 53]
  [54 55 56]
  [57 58 59]]

 [[60 61 62]
  [63 64 65]
  [66 67 68]
  [69 70 71]
  [72 73 74]]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
You cant multiply them because the dimensions dont line up


In [17]:
#17. Extract all the contiguous 3x3 blocks from a random 10x10 matrix
    #NC: Got this from the internet. Dont really understand
x = np.random.randint(0,5,(10,10))
print(x)

n = 3
i = 1 + (x.shape[0]-3)
j = 1 + (x.shape[1]-3)
result = np.lib.stride_tricks.as_strided(x, shape=(i, j, n, n), strides = x.strides + x.strides)
print(result)

[[3 4 3 3 1 2 2 4 0 0]
 [3 3 4 2 3 3 3 0 1 0]
 [1 4 4 4 0 0 4 2 2 0]
 [0 3 2 3 1 1 3 2 3 4]
 [4 4 3 0 3 4 3 3 1 4]
 [3 0 2 2 2 1 0 2 4 4]
 [2 0 4 3 2 0 3 0 1 4]
 [1 0 1 3 2 1 0 3 4 1]
 [2 4 1 3 4 0 2 2 3 3]
 [0 1 0 2 4 3 0 3 1 4]]
[[[[3 4 3]
   [3 3 4]
   [1 4 4]]

  [[4 3 3]
   [3 4 2]
   [4 4 4]]

  [[3 3 1]
   [4 2 3]
   [4 4 0]]

  [[3 1 2]
   [2 3 3]
   [4 0 0]]

  [[1 2 2]
   [3 3 3]
   [0 0 4]]

  [[2 2 4]
   [3 3 0]
   [0 4 2]]

  [[2 4 0]
   [3 0 1]
   [4 2 2]]

  [[4 0 0]
   [0 1 0]
   [2 2 0]]]


 [[[3 3 4]
   [1 4 4]
   [0 3 2]]

  [[3 4 2]
   [4 4 4]
   [3 2 3]]

  [[4 2 3]
   [4 4 0]
   [2 3 1]]

  [[2 3 3]
   [4 0 0]
   [3 1 1]]

  [[3 3 3]
   [0 0 4]
   [1 1 3]]

  [[3 3 0]
   [0 4 2]
   [1 3 2]]

  [[3 0 1]
   [4 2 2]
   [3 2 3]]

  [[0 1 0]
   [2 2 0]
   [2 3 4]]]


 [[[1 4 4]
   [0 3 2]
   [4 4 3]]

  [[4 4 4]
   [3 2 3]
   [4 3 0]]

  [[4 4 0]
   [2 3 1]
   [3 0 3]]

  [[4 0 0]
   [3 1 1]
   [0 3 4]]

  [[0 0 4]
   [1 1 3]
   [3 4 3]]

  [[0 4 2]
   [1 3 2]
   [4 3 

In [18]:
#18. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?
 #NC: Got this from the internet. Dont really understand
a=np.arange(256).reshape((16,16))
b = 4
c = np.add.reduceat(np.add.reduceat(a, np.arange(0, a.shape[0], b), axis=0),
                                       np.arange(0, a.shape[1], b), axis=1)
print (a)
print (c)



[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
 [ 16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31]
 [ 32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47]
 [ 48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63]
 [ 64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95]
 [ 96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111]
 [112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127]
 [128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143]
 [144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175]
 [176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191]
 [192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207]
 [208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223]
 [224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 

In [27]:
#Assignment2:
#Calculate summary statistics: mean, std, 0%,10%,20%,…, percentiles (look for how to do that in the numpy documentation) based on the data in the dataset folder. 
import pandas as pd
sample_data=pd.read_csv(r'T:\Users\NCiaccia\Data Science Academy\Week 2\dataset\sample_test_data.csv')
print(sample_data.head())
#get rid of non numeric column
sample_data2=sample_data.drop(columns=['playerID'])
arr=sample_data2.to_numpy()
mean=np.mean(arr)
print(f"Mean is {mean}")
sd=np.std(arr)
print(f"SD is {sd}")

#One way to get percentiles
percentiles=[0,10,20,30,40,50,60,70,80,90,100]
for p in percentiles:
    print (f'{p}th percentile is %s'%(str(np.percentile(arr,p))))

#Get percentiles avoding the for loop
print ('Percentiles: 0,10,20,30,40,50,60,70,80,90,100 of array \n%s\n'%np.percentile(sample_data2, [0,10,20,30,40,50,60,70,80,90,100]))


   item1  item2  item3  item4  item5  item6  item7  item8  item9  item10  \
0      1      1      2      1      1      1      1      1      0       1   
1      1      1      2      1      1      1      1      2      2       0   
2      1      1      1      1      1      1      0      2      2       1   
3      1      1      2      1      1      1      1      2      0       1   
4      1      0      1      0      0      1      1      2      2       0   

   item11        playerID  
0       1  tetralogue1001  
1       1  tetralogue1002  
2       1  tetralogue1007  
3       1  tetralogue1011  
4       0  tetralogue1013  
Mean is 0.9879679144385026
SD is 0.6731001300451318
0th percentile is 0.0
10th percentile is 0.0
20th percentile is 0.0
30th percentile is 1.0
40th percentile is 1.0
50th percentile is 1.0
60th percentile is 1.0
70th percentile is 1.0
80th percentile is 2.0
90th percentile is 2.0
100th percentile is 2.0
Percentiles: 0,10,20,30,40,50,60,70,80,90,100 of array 
[0. 0. 0. 1. 1

In [28]:
#Assignment 3: 
#Generate 2 random gaussian distributions and run a t-test to see differences
from scipy import stats
a = np.random.normal(0, 50, size=20)
b = np.random.normal(1, 35, size=10)
print(a)
print(b)
stats.ttest_ind(a, b)

[-31.26798095 -32.68268686  -4.42012364 127.88559982   8.4451822
  -3.26265222  68.29622985 -10.38077806 -60.61169066  14.10936527
  58.86095824 -91.4772793  -48.83530399 -37.88764962  83.52766411
 -71.83380682 -29.04479499  25.38647979  77.34339967  -1.41934346]
[ 58.16988678   1.18483043  40.04328182  11.51252479  -7.50348141
  23.94948347  -4.01978012 -32.31603866  17.21479619  12.22057362]


Ttest_indResult(statistic=-0.5239019131199407, pvalue=0.6044693858076157)